// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_icons_dart icons;
  final _assets_images_dart images;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Inter_VariableFont_opsz_wght_ttf = 'assets/fonts/Inter-VariableFont_opsz,wght.ttf';
  final Inter_18pt_Black_ttf = 'assets/fonts/Inter_18pt-Black.ttf';
  final Inter_18pt_Bold_ttf = 'assets/fonts/Inter_18pt-Bold.ttf';
  final Inter_18pt_ExtraBold_ttf = 'assets/fonts/Inter_18pt-ExtraBold.ttf';
  final Inter_18pt_ExtraLight_ttf = 'assets/fonts/Inter_18pt-ExtraLight.ttf';
  final Inter_18pt_Light_ttf = 'assets/fonts/Inter_18pt-Light.ttf';
  final Inter_18pt_Medium_ttf = 'assets/fonts/Inter_18pt-Medium.ttf';
  final Inter_18pt_Regular_ttf = 'assets/fonts/Inter_18pt-Regular.ttf';
  final Inter_18pt_SemiBold_ttf = 'assets/fonts/Inter_18pt-SemiBold.ttf';
  final Inter_18pt_Thin_ttf = 'assets/fonts/Inter_18pt-Thin.ttf';
  final OFL_txt = 'assets/fonts/OFL.txt';
  final README_txt = 'assets/fonts/README.txt';
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final buisness_icon_png = 'assets/icons/buisness_icon.png';
  final chat_bubble_icon_png = 'assets/icons/chat_bubble_icon.png';
  final chat_icon_png = 'assets/icons/chat_icon.png';
  final people_icon_png = 'assets/icons/people_icon.png';
  final star_icon_png = 'assets/icons/star_icon.png';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final doctor1_png = 'assets/images/doctor1.png';
  final doctor2_png = 'assets/images/doctor2.png';
  final doctor3_png = 'assets/images/doctor3.png';
  final doctor4_png = 'assets/images/doctor4.png';
  final doctor_element_png = 'assets/images/doctor_element.png';
  final logo_png = 'assets/images/logo.png';
  final notebook_png = 'assets/images/notebook.png';
  final onboarding_screen_1_png = 'assets/images/onboarding-screen-1.png';
  final onboarding_screen_2_png = 'assets/images/onboarding-screen-2.png';
  final onboarding_screen_3_png = 'assets/images/onboarding-screen-3.png';
  final SyrianFlag_png = 'assets/images/SyrianFlag.png';
}
